{{- if .Values.videoWorker.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-findface-video-worker-recorder
  labels:
    app.kubernetes.io/name: findface
    app.kubernetes.io/component: video-worker-recorder
spec:
  accessModes:
{{- range .Values.videoWorker.recorder.pvc.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.videoWorker.recorder.pvc.size }}
{{- if .Values.videoWorker.recorder.pvc.storageClassName }}
  storageClassName: {{ .Values.videoWorker.recorder.pvc.storageClassName }}
{{- end }}
{{- end }}
