{{- if .Values.videoWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: findface-video-worker
  labels:
    app.kubernetes.io/name: findface
    app.kubernetes.io/component: video-worker
{{- with .Values.videoWorker.service.headless.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.videoWorker.service.headless.publishNotReadyAddresses }}
  selector:
    app.kubernetes.io/name: findface
    app.kubernetes.io/component: video-worker
  ports:
    - name: streamer
      protocol: TCP
      port: {{ .Values.videoWorker.service.port }}
      targetPort: {{ .Values.videoWorker.service.port }}
{{- end }}
