{{- if .Values.videoWorker.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: findface-video-worker
  labels:
    app.kubernetes.io/name: findface
    app.kubernetes.io/component: video-worker
spec:
  serviceName: findface-video-worker
  replicas: {{ .Values.videoWorker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: findface
      app.kubernetes.io/component: video-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: findface
        app.kubernetes.io/component: video-worker
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      hostNetwork: {{ .Values.videoWorker.hostNetwork }}
      dnsPolicy: {{ if .Values.videoWorker.hostNetwork }}ClusterFirstWithHostNet{{ else }}{{ .Values.videoWorker.dnsPolicy }}{{ end }}
{{- with .Values.videoWorker.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: findface-video-worker
          image: "{{ .Values.videoWorker.image.repository }}:{{ .Values.videoWorker.image.tag }}"
          imagePullPolicy: {{ .Values.videoWorker.image.pullPolicy }}
          args:
{{- range .Values.videoWorker.args }}
            - {{ . | quote }}
{{- end }}
          env:
{{- if .Values.videoWorker.service.loadBalancer.enabled }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- end }}
            - name: CUDA_VISIBLE_DEVICES
              value: {{ .Values.videoWorker.cudaVisibleDevices | quote }}
          ports:
            - name: streamer
              containerPort: {{ .Values.videoWorker.service.port }}
              protocol: TCP
{{- with .Values.videoWorker.containerSecurityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
            requests:
              cpu: {{ .Values.videoWorker.resources.requests.cpu }}
              memory: {{ .Values.videoWorker.resources.requests.memory }}
            limits:
              cpu: {{ .Values.videoWorker.resources.limits.cpu }}
              memory: {{ .Values.videoWorker.resources.limits.memory }}
{{- if .Values.videoWorker.gpu.enabled }}
              nvidia.com/gpu: {{ .Values.videoWorker.gpu.count }}
{{- end }}
          volumeMounts:
            - name: video-worker-config
              mountPath: /etc/findface-video-worker.yaml
{{- if .Values.videoWorker.service.loadBalancer.enabled }}
              subPathExpr: $(POD_NAME).yaml
{{- else }}
              subPath: findface-video-worker.yaml
{{- end }}
              readOnly: true
            - name: models
              mountPath: /usr/share/findface-data/models
              readOnly: true
            - name: video-worker-cache
              mountPath: /var/cache/findface/models_cache
            - name: video-worker-recorder
              mountPath: /var/cache/findface/video-worker-recorder
      volumes:
        - name: video-worker-config
          configMap:
            name: findface-video-worker
        - name: models
          persistentVolumeClaim:
            claimName: findface-models
{{- with .Values.videoWorker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.videoWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.videoWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: video-worker-cache
        labels:
          app.kubernetes.io/name: findface
          app.kubernetes.io/component: video-worker-cache
      spec:
        accessModes:
{{- range .Values.videoWorker.cache.pvc.accessModes }}
          - {{ . }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.videoWorker.cache.pvc.size }}
{{- if .Values.videoWorker.cache.pvc.storageClassName }}
        storageClassName: {{ .Values.videoWorker.cache.pvc.storageClassName }}
{{- end }}
    - metadata:
        name: video-worker-recorder
        labels:
          app.kubernetes.io/name: findface
          app.kubernetes.io/component: video-worker-recorder
      spec:
        accessModes:
{{- range .Values.videoWorker.recorder.pvc.accessModes }}
          - {{ . }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.videoWorker.recorder.pvc.size }}
{{- if .Values.videoWorker.recorder.pvc.storageClassName }}
        storageClassName: {{ .Values.videoWorker.recorder.pvc.storageClassName }}
{{- end }}
{{- end }}
