{{- if and .Values.extractionApi.enabled .Values.extractionApi.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: findface-extraction-api
  labels:
    app.kubernetes.io/name: findface
    app.kubernetes.io/component: extraction-api
{{- with .Values.extractionApi.service.headless.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.extractionApi.service.headless.publishNotReadyAddresses }}
  selector:
    app.kubernetes.io/name: findface
    app.kubernetes.io/component: extraction-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.extractionApi.service.port }}
      targetPort: {{ .Values.extractionApi.service.port }}
{{- end }}
